package Database_TermProject;

//------------------------------------------------------------------------------------------------------//
// Notes:                                                                                               //
//      - Once adopted an animal is removed from the database, review deletion is done by a cascade		//
//      - An animal may have any number of reviews (including none)                                     //
//      - Identifiers for animals auto-generated by the auto-increment feature provided by SQL          //
//      - Traits and species are NOT predefined,users may provide any they wish                         //
//------------------------------------------------------------------------------------------------------//

public class Review {
	protected int reviewID;
	protected int animalID;
	protected String rating;
	protected String comment;
	protected String author;

	public Review() {}

	public Review(int reviewID, int animalID, String rating, String comment, String author) {
		this(animalID, rating, comment, author);
		this.reviewID = reviewID; }

	public Review(int animalID, String rating, String comment, String author) {
		this.animalID = animalID;
		this.rating = rating;
		this.comment = comment;
		this.author = author; }

	public void setReviewID(int id) { this.reviewID = id; }
	public void setAnimalID(int animalID) { this.animalID = animalID; }
	public void setRating(String rating) { this.rating = rating; }
	public void setAuthor(String author) { this.author = author; }
	public void setComment(String comment) { this.comment = comment;}

	public int getreviewID() { return reviewID; }                               // !! DO NOT CHANGE LOWERCASE 'r'
	public int getanimalID() { return animalID; }                               // !! DO NOT CHANGE LOWERCASE 'a'
	public String getrating() { return rating; }                                // !! DO NOT CHANGE LOWERCASE 'r'
	public String getcomment() { return comment; }                              // !! DO NOT CHANGE LOWERCASE 'c'
	public String getauthor() { return author; }                                // !! DO NOT CHANGE LOWERCASE 'a'

}// END CLASS [ Review ]