package Database_TermProject;

//------------------------------------------------------------------------------------------------------//
// Notes:                                                                                               //
//      - Once adopted an animal is removed from the database, review deletion is done by a cascade		//
//      - An animal may have any number of reviews (including none)                                     //
//      - Identifiers for animals auto-generated by the auto-increment feature provided by SQL          //
//      - Traits and species are NOT predefined,users may provide any they wish                         //
//------------------------------------------------------------------------------------------------------//

public class Review {
	protected int reviewID;
	protected int animalID;
	protected String rating;
	protected String comments;
	protected String author;

	public Review() {}

	public Review(int reviewID, int animalID, String rating, String comments, String author) {
		this(animalID, rating, comments, author);
		this.reviewID = reviewID; }

	public Review(int animalID, String rating, String comments, String author) {
		this.animalID = animalID;
		this.rating = rating;
		this.comments = comments;
		this.author = author; }

	public void setReviewID(int id) { this.reviewID = id; }
	public void setAnimalID(int animalID) { this.animalID = animalID; }
	public void setRating(String rating) { this.rating = rating; }
	public void setAuthor(String author) { this.author = author; }
	public void setComments(String comments) { this.comments = comments;}

	public int getreviewID() { return reviewID; }
	public int getanimalID() { return animalID; }
	public String getrating() { return rating; }
	public String getcomment() { return comments; }
	public String getauthor() { return author; }

}// END CLASS [ Review ]